// Generated by cli/zoom/codegen.ts (user / userToken). Do not edit by hand.

export type Path = {
	/**
	 * The user's user ID or email address. For user-level apps, pass the `me` value.
	 */
	userId: string;
};

export type Query = {
	/**
	 * The user token type.
	 * * `zak` - A Zoom Access Key (ZAK) is used to generate a URL to start meetings. See [Getting a Zoom Access Key (ZAK)](https://developers.zoom.us/docs/meeting-sdk/auth/#start-meetings-and-webinars-with-a-zoom-users-zak-token) for details. The ZAK's expiration time is two hours. For API users, the expiration time is 90 days. An API user is a user created via the `custCreate` action in the **[Create users](https://marketplace.zoom.us/docs/api-reference/zoom-api/methods/#operation/userCreate)** API. The maximum length of this value is `512`.
	 * * `token` - **Deprecated** A Zoom token. This token expires in 14 days. You must make the request again after expiration to receive a new token. This query parameter returns a null value if the user signed in to Zoom via Google or Facebook. The maximum length of this value is `512`.
	 * * `onbehalf` - A Zoom token that establishes a delegation relationship between a Zoom user and a Meeting SDK app. It allows the SDK app to join the same meeting as the Zoom user and act on their behalf in an assistant role. The SDK app cannot use this token to join meetings independently without the Zoom user present. This token expires in 2 hours; you must request a new token after it expires.
	 *
	 *  This value defaults to `token`.
	 */
	type?: 'token' | 'zak' | 'onbehalf';
	/**
	 * The ZAK/onbehalf expiration time to live (TTL), in seconds. To update the user's ZAK/onbehalf TTL, use this field with the `zak` or `onbehalf` value for the `type` query parameter.
	 *
	 * Defaults to `7200` or `7776000` (90 days) for API users. The maximum value is one year.
	 */
	ttl?: number;
	/**
	 * The meeting's ID, use this field with the `onbehalf` value for the `type` query parameter.
	 */
	meeting_id?: string;
};

export type ResponseBody200 = {
	/**
	 * The user's ZAK or token value.
	 */
	token?: string;
};
