// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vUserTokenPath = v.object({
	userId: v.string(),
});

export const vUserTokenQuery = v.object({
	type: v.optional(v.picklist(['token', 'zak', 'onbehalf']), 'token'),
	ttl: v.optional(v.pipe(v.number(), v.integer()), 7200),
	meeting_id: v.optional(v.string()),
});

/**
 * **HTTP Status Code:** `200`
 *
 * If the request uses `type=token` and the account is not on the allowlist, the response will be: "Token is no longer supported. Please use ZAK token instead." If the account is on the allowlist with `type=token`, or if `type=zak` is used, the token will be returned.
 */
export const vUserTokenResponse = v.object({
	token: v.optional(v.string()),
});
