// Generates request/response types and response valibot schemas for one Zoom API operation.
//
// Usage: node cli/zoom/codegen.ts <meeting|user> <operationId> <outDir>
// Example: node cli/zoom/codegen.ts user userToken src/meeting/zoom/users/GET/token
//
// Request types come from json-schema-to-typescript (JSDoc preserved). Response schemas come
// from json-schema-to-valibot, which keeps only the first `allOf` member; review those by hand.

import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { compile } from 'json-schema-to-typescript';
import { jsonSchemaToValibot } from 'json-schema-to-valibot';

const specs = {
	meeting: 'https://developers.zoom.us/api-specs/zoom-api/methods/ZoomMeetingAPI-spec.json',
	user: 'https://developers.zoom.us/api-specs/user/methods/ZoomUserAPI-spec.json',
};

type Schema = Record<string, unknown>;
type Parameter = {
	name: string;
	in: 'path' | 'query';
	required?: boolean;
	schema: Schema;
	description?: string;
};
type Content = Record<string, { schema?: Schema }> | undefined;
type Operation = {
	operationId: string;
	parameters?: Parameter[];
	requestBody?: { content: Content };
	responses: Record<string, { content?: Content }>;
};

const [specName, operationId, outDir] = process.argv.slice(2);
if (!specName || !operationId || !outDir)
	throw new Error('Usage: <meeting|user> <operationId> <outDir>');
if (!(specName in specs)) throw new Error(`Unknown spec: ${specName}`);

const spec = (await (await fetch(specs[specName as keyof typeof specs])).json()) as {
	paths: Record<string, Record<string, Operation>>;
};

const operation = Object.values(spec.paths)
	.flatMap((methods) => Object.values(methods))
	.find((op) => op.operationId === operationId);
if (!operation) throw new Error(`Operation not found: ${operationId}`);

const parametersToSchema = (location: Parameter['in']) => {
	const parameters = (operation.parameters ?? []).filter((p) => p.in === location);
	if (!parameters.length) return null;
	return {
		type: 'object',
		properties: Object.fromEntries(
			parameters.map((p) => [p.name, { ...p.schema, description: p.description }]),
		),
		required: parameters.filter((p) => p.required).map((p) => p.name),
		additionalProperties: false,
	};
};

const jsonSchema = (content: Content) => content?.['application/json']?.schema ?? null;

const types: Array<[name: string, schema: Schema]> = [];
const responses: Array<[name: string, schema: Schema]> = [];

const path = parametersToSchema('path');
const query = parametersToSchema('query');
const requestBody = jsonSchema(operation.requestBody?.content);
if (path) types.push(['Path', path]);
if (query) types.push(['Query', query]);
if (requestBody) types.push(['RequestBody', requestBody]);
for (const [status, response] of Object.entries(operation.responses)) {
	const schema = jsonSchema(response.content);
	if (schema) responses.push([`ResponseBody${status}`, schema]);
}

const banner = `// Generated by cli/zoom/codegen.ts (${specName} / ${operationId}). Do not edit by hand.\n`;

const typesSource = await Promise.all(
	[...types, ...responses].map(([name, schema]) =>
		compile(schema as never, name, {
			bannerComment: '',
			format: false,
			additionalProperties: false,
		}),
	),
);

const schemasSource = responses.map(([name, schema]) =>
	jsonSchemaToValibot(schema as never, { name: `${name}Schema`, module: 'esm' })
		.replace(/^import \* as v from ['"]valibot['"];?\n+/, '')
		.trimEnd(),
);

mkdirSync(resolve(outDir), { recursive: true });

const files = {
	'types.ts':
		banner +
		'\n' +
		typesSource.join('\n').replaceAll(/export interface (\w+) \{/g, 'export type $1 = {'),
	'schemas.ts': banner + "\nimport * as v from 'valibot';\n\n" + schemasSource.join('\n\n') + '\n',
};

for (const [file, source] of Object.entries(files)) writeFileSync(resolve(outDir, file), source);

execFileSync(
	'pnpm',
	['exec', 'oxfmt', ...Object.keys(files).map((file) => resolve(outDir, file))],
	{
		stdio: 'inherit',
	},
);
